### ISSUE TITLE
Update python2/python3 selection during update

### ISSUE THREAD

**Issue by iperi** [sakaki-/genup#5]
I noticed that after world update selection of python2/3 interpreter isn't updated. I'm talking about small version bumps like from 3.3 to 3.4. It is easy to update through command line: `eselect python update --python2` and `eselect python update --python3`. After running `emerge --depclean` without this update symlink could become invalid.

For clarification: I'm not talking about global python interpreter selection (which should be untouched).

What do you think?

**Comment by sakaki-** [comment]
Hi, yes this would probably be sensible, perhaps as an option though rather than as default behaviour - I guess if someone has e.g. python 3.4 and 3.5 (which are in separate slots) installed, with 3.4 as default, they might get annoyed if `eselect python update --python3` kept automatically selecting 3.5 on them...

**Comment by sakaki-** [comment]
Hi, I've just released `genup-1.0.11`, which adds an `/etc/genup/updaters.d` directory. `genup` will run all executable files (or symlinks to executable files) found at the top level in that directory, at the end of its run (unless the `--no-custom-updaters` option is passed), and will immediately exit with an error should any of them return a non-zero exit status. The ebuild includes some examples, in `/etc/genup/updaters.d/examples`; copy or link these into the `/etc/genup/updaters.d` directory to have them run. The files `/etc/genup/updaters.d/examples/20-python2-version.sh` and `/etc/genup/updaters.d/examples/21-python3-version.sh` should hopefully address your use case if copied up.

I'm very open to pull requests for more sophisticated handlers to place in the `examples` directory; please address any of those to the [genup](https://github.com/sakaki-/sakaki-tools/tree/master/app-portage/genup) package within `sakaki-tools`. Thanks!

**Comment by iperi** [comment]
I have one doubt - the `python-updater` is run before those scripts. So, after changing python version is not run. I have no idea what actually this `python-updater` is doing, but is it going to work with this script running order?

**Comment by sakaki-** [comment]
You can always modify the `20-python2-version.sh` / `21-python3-version.sh` scripts to call `python-updater` themselves, after they call `eselect python update --python2 / --python3`. But I don't think that's necessary, as `python-updater` uses the `portage` info to find installed versions, rather than just the symlink. Will check.

**Comment by sakaki-** [comment]
I think this is OK as is, so closing, but if you get problems with it please re-open or submit a PR on the updater in question (for example, if you want to add in a call to `python-updater`).
Best, sakaki
